version: "3"
services:
  web:
    build: # could use user build: . if there is only one dockerfile
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    environment:
      - MAGIC_NAME=JOHN
    volumes:
      - /app/node_modules
      - .:/app
    command: ["npm", "start"]
